version: '3'
services:

  webapp:
    image: header
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PORT: 3000
      pghost: postgres
      pguser: Kevin
      pgpass: docker
      dburl: http://ec2-34-201-249-210.compute-1.amazonaws.com:3000
    ports: 
      - 3000:3000

  proxy:
    image: whelp-proxy
    ports:
      - 80:2000

  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: Kevin
      POSTGRES_DB: yelp
    ports:
      - "5432:5432"